POST https://sea-lion-app-rd2lz.ondigitalocean.app/api/leads
Content-Type: application/json

{
  "data":{
    "Name": "Test name from local",
    "Email": "test@test.com",
    "Message": "Some test message from local"
  }
}

###
GET https://sea-lion-app-rd2lz.ondigitalocean.app/api/skills?populate=deep,2

###
GET https://sea-lion-app-rd2lz.ondigitalocean.app/api/projects?populate=deep,3
